### ISSUE TITLE
bootstrap cards showing 3 events to happen at the olympics

### ISSUE THREAD

**Issue by rajoouddin** [Sally077/Paris-Olympics#10]
Using bootstrap to create 3 cards that will display 3 events that will be taking place at the olympics
- [x] create 3 bootstrap cards
- [x] each card to show details of an olympic event
- [x] each card to have an image of that event
- [x] maybe buttons to link them to find out more (if there's an official site)

---
Something like:
![image](https://user-images.githubusercontent.com/24569164/217655083-0fe1dadd-25e5-4ed3-8151-8e6043e7400f.png)

**Comment by Sandramihaela** [comment]
I have created the 3 Bootstrap cards and pushed to GitHub for approval.
