### ISSUE TITLE
currency converter

### ISSUE THREAD

**Issue by rajoouddin** [Sally077/Paris-Olympics#7]
we need to create a section to convert the currency to EUR
- [x] a box to enter a currency
- [x] api to pull through the current conversion rate for EUR
- [x] a button to carry out the conversion
- [x] a box where the converted amount is displayed
---
Something to look something like this;

![image](https://user-images.githubusercontent.com/24569164/217653274-ee868fe0-0883-4de6-8014-7ae67fcc4744.png)

**Comment by reaganrodriguez** [comment]
Added to my branch
